version: 3.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern "\$version\$" -Replacement "$env:appveyor_build_version" -Path .\Source\DateTimeExtensions.nuspec -Overwrite

configuration: Release

build:
  project: Exceptionless.DateTimeExtensions.sln
  publish_nuget: true
  publish_nuget_symbols: true