version: 3.0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

configuration: Release

build:
  project: Exceptionless.DateTimeExtensions.sln
  publish_nuget: true
  publish_nuget_symbols: true